In [10]:
import numpy as np# Step 1

# Step 1
array_1d = np.arange(1, 21)

# Step 2
array_2d = array_1d.reshape(4, 5)

# Step 3
array_2d[:, -1] = 0

# Step 4
flattened_array = array_2d.flatten()
print("Flattened Array:", flattened_array)



Flattened Array: [ 1  2  3  4  0  6  7  8  9  0 11 12 13 14  0 16 17 18 19  0]


In [9]:
# Generate random 5x5 array
array_2d_random = np.random.randint(10, 50, size=(5, 5))
print("Generated 2D Array:\n", array_2d_random)

# Row-wise statistics
print("\nRow-wise statistics:")
for i, row in enumerate(array_2d_random):
    print(f"Row {i}: Mean={row.mean()}, Sum={row.sum()}, Min={row.min()}, Max={row.max()}")

# Column-wise statistics
print("\nColumn-wise statistics:")
for i in range(array_2d_random.shape[1]):
    column = array_2d_random[:, i]
    print(f"Column {i}: Mean={column.mean()}, Sum={column.sum()}, Min={column.min()}, Max={column.max()}")


Generated 2D Array:
 [[21 27 40 26 10]
 [29 47 39 32 14]
 [18 13 27 30 29]
 [28 15 14 25 42]
 [39 24 26 20 14]]

Row-wise statistics:
Row 0: Mean=24.8, Sum=124, Min=10, Max=40
Row 1: Mean=32.2, Sum=161, Min=14, Max=47
Row 2: Mean=23.4, Sum=117, Min=13, Max=30
Row 3: Mean=24.8, Sum=124, Min=14, Max=42
Row 4: Mean=24.6, Sum=123, Min=14, Max=39

Column-wise statistics:
Column 0: Mean=27.0, Sum=135, Min=18, Max=39
Column 1: Mean=25.2, Sum=126, Min=13, Max=47
Column 2: Mean=29.2, Sum=146, Min=14, Max=40
Column 3: Mean=26.6, Sum=133, Min=20, Max=32
Column 4: Mean=21.8, Sum=109, Min=10, Max=42


In [11]:

# Step 1
identity_matrix = np.eye(4)

# Step 2
identity_matrix[np.diag_indices(4)] += 5

# Step 3
identity_matrix[-1, :] = 1
print("Modified Matrix:\n", identity_matrix)

Modified Matrix:
 [[6. 0. 0. 0.]
 [0. 6. 0. 0.]
 [0. 0. 6. 0.]
 [1. 1. 1. 1.]]


In [12]:
# Generate the array
random_array = np.random.randint(0, 21, size=15)
print("Generated Array:", random_array)

# Count occurrences of each unique value
unique_values, counts = np.unique(random_array, return_counts=True)
print("\nOccurrences of each unique value:")
for value, count in zip(unique_values, counts):
    print(f"Value {value}: {count} times")

# Find indices of elements greater than 10
indices_greater_than_10 = np.where(random_array > 10)[0]
print("\nIndices of elements greater than 10:", indices_greater_than_10)

Generated Array: [17  5  3 17 16  0 10  1 12 17  5  6 13 15  3]

Occurrences of each unique value:
Value 0: 1 times
Value 1: 1 times
Value 3: 2 times
Value 5: 2 times
Value 6: 1 times
Value 10: 1 times
Value 12: 1 times
Value 13: 1 times
Value 15: 1 times
Value 16: 1 times
Value 17: 3 times

Indices of elements greater than 10: [ 0  3  4  8  9 12 13]


In [13]:
float_array = np.random.rand(3, 4)

# Step 2
float_array = np.round(float_array, 2)

# Step 3
float_array[:, 1] = 0.5
print("Modified Array:\n", float_array)

Modified Array:
 [[0.39 0.5  0.44 0.79]
 [0.48 0.5  0.38 0.75]
 [0.63 0.5  0.17 0.71]]
